version: "3.8"
services:
  mongo:
    image: mongo:4
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"

volumes:
  mongo_data:
