version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://<YOUR_BACKEND_HOST>:5000/}
    restart: always
    environment:
      PORT: ${FRONTEND_PORT:-3000}
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
