version: "3.8"

services:
  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo01}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-testdb}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"

  backend:
    build: ../backend
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      MONGO_URI: ${MONGO_URI:-mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-mongo01}@mongo:${MONGO_PORT:-27017}/${MONGO_INITDB_DATABASE:-testdb}}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      MICROSOFT_TENANT_ID: ${MICROSOFT_TENANT_ID:-common}
      MICROSOFT_REDIRECT_URI: ${MICROSOFT_REDIRECT_URI}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - mongo
    ports:
      - "${BACKEND_PORT:-5000}:5000"

volumes:
  mongo_data:
