name: Frontend Deploy

on:
    push:
        paths:
            - "frontend/**"
            - ".github/workflows/frontend-deploy.yml"
        branches:
            - main
    workflow_dispatch:

jobs:
    frontend:
        name: Build & Test Frontend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint --if-present

            - name: Build frontend
              run: npm run build

            - name: Run frontend tests
              env:
                  CI: true
              run: |
                  echo "Running frontend tests..."
                  for i in 1 2 3; do
                    npm test && break || (echo "Retrying tests ($i/3)" && sleep 5)
                  done

    deploy:
        name: Deploy Frontend Stack
        runs-on: ubuntu-latest
        needs: frontend
        if: ${{ success() }}
        steps:
            - name: Trigger Portainer Frontend Deploy
              run: |
                  echo "Deploying frontend stack..."
                  curl -s -X POST "${{ secrets.PORTAINER_FRONTEND_WEBHOOK }}" || exit 1
